version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/Mern/back-end
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: application_start.sh
      timeout:
